"""Build and save the CyberLens classifier.

Run once before starting the app:  python train_model.py

Generates the synthetic corpus (corpus.py), pushes it through the *same*
preprocessing the web app uses, trains a TF-IDF + numeric LogisticRegression
pipeline, prints an honest evaluation on a stratified held-out split, and
saves models/cyberlens_model.joblib plus models/metrics.json.
"""
from __future__ import annotations

import json
import os
import time
from datetime import datetime, timezone

import joblib
import pandas as pd
import sklearn
from sklearn.compose import ColumnTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

import config
from core.preprocess import preprocess
from corpus import corpus_blocks

SEED = 42


def build_frame(blocks: list[dict]) -> pd.DataFrame:
    """Corpus rows -> the canonical DataFrame preprocess() expects."""
    df = pd.DataFrame(blocks).rename(columns={"label": "label_original"})
    df.insert(0, "row_id", range(1, len(df) + 1))
    for col in ("dst_ip", "dst_port", "username", "bytes", "duration", "status"):
        if col not in df.columns:
            df[col] = pd.NA
    return df


def build_pipeline() -> Pipeline:
    """TF-IDF (word + char) on event text, scaled numeric behavioural features."""
    text = "event_clean"
    word_tfidf = TfidfVectorizer(ngram_range=(1, 2), min_df=2, max_features=20_000,
                                 sublinear_tf=True)
    char_tfidf = TfidfVectorizer(analyzer="char_wb", ngram_range=(3, 5),
                                 min_df=3, max_features=15_000, sublinear_tf=True)
    numeric = Pipeline([
        ("impute", SimpleImputer(strategy="median")),
        ("scale", StandardScaler()),
    ])
    preprocessor = ColumnTransformer([
        ("word", word_tfidf, text),
        ("char", char_tfidf, text),
        ("num", numeric, config.MODEL_NUMERIC_FEATURES),
    ])
    # Logistic regression handles the sparse stacked features well, trains in
    # seconds, and gives calibrated-enough probabilities for the severity rule.
    clf = LogisticRegression(C=5.0, max_iter=2000, random_state=SEED)
    return Pipeline([("features", preprocessor), ("clf", clf)])


def main() -> None:
    started = time.time()
    print("Generating synthetic corpus ...")
    blocks = corpus_blocks(seed=SEED)
    df = build_frame(blocks)
    print(f"  {len(df):,} labelled events")

    print("Preprocessing (same code path as the web app) ...")
    clean, summary = preprocess(df)
    clean = clean[clean["event_clean"].str.len() > 0]
    print(f"  {len(clean):,} rows after dedupe/cleaning "
          f"({summary['duplicates_removed']} duplicates removed)")

    X = clean[config.MODEL_NUMERIC_FEATURES + [config.TEXT_FEATURE]].copy()
    X[config.TEXT_FEATURE] = X[config.TEXT_FEATURE].astype(object)
    y = clean["label_original"].astype(str)

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, stratify=y, random_state=SEED
    )

    print("Training TF-IDF + LogisticRegression pipeline ...")
    pipe = build_pipeline()
    pipe.fit(X_train, y_train)

    print("\nHeld-out classification report (synthetic data):")
    y_pred = pipe.predict(X_test)
    print(classification_report(y_test, y_pred, digits=3))
    labels = sorted(y.unique())
    print("Confusion matrix (rows = true, cols = predicted):")
    print(pd.DataFrame(
        confusion_matrix(y_test, y_pred, labels=labels),
        index=[f"true {l}" for l in labels],
        columns=labels,
    ).to_string())

    accuracy = float((y_pred == y_test).mean())
    report = classification_report(y_test, y_pred, output_dict=True)

    metrics = {
        "model": "TF-IDF (word 1-2g + char 3-5g) + scaled numeric features + LogisticRegression",
        "trained_at": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        "accuracy": round(accuracy, 4),
        "per_class": {
            label: {
                "precision": round(report[label]["precision"], 3),
                "recall": round(report[label]["recall"], 3),
                "f1": round(report[label]["f1-score"], 3),
                "support": int(report[label]["support"]),
            } for label in labels
        },
        "train_rows": int(len(X_train)),
        "test_rows": int(len(X_test)),
        "corpus_rows": int(len(clean)),
        "numeric_features": config.MODEL_NUMERIC_FEATURES,
        "text_feature": config.TEXT_FEATURE,
        "sklearn_version": sklearn.__version__,
        "data_source": "synthetic corpus generated by corpus.py (seeded, reproducible)",
    }
    os.makedirs(os.path.dirname(config.METRICS_PATH), exist_ok=True)
    with open(config.METRICS_PATH, "w", encoding="utf-8") as fh:
        json.dump(metrics, fh, indent=2)

    joblib.dump(pipe, config.MODEL_PATH)
    print(f"\nAccuracy on held-out synthetic split: {accuracy:.1%}")
    print(f"Saved {config.MODEL_PATH}")
    print(f"Saved {config.METRICS_PATH}")
    print(f"Done in {time.time() - started:.1f}s")


if __name__ == "__main__":
    main()
